CONFIG_NAME					= Nisse
THORSANVIL_ROOT				?= $(realpath ../../)

LDLIBS_EXTERN_BUILD			= ThorSerialize event BoostCoRoutine
TARGET						= Nisse.lib
DEFER_LIBS					= NisseServer NisseHTTP

include $(THORSANVIL_ROOT)/build/tools/Makefile
