THORSANVIL_ROOT             = $(realpath ../../)

TARGET						= NisseServer.defer
NAMESPACE					= ThorsAnvil::Nisse
DEFER_NAME					= Nisse
FILE_WARNING_FLAGS			+= -Wno-dollar-in-identifier-extension

include $(THORSANVIL_ROOT)/build/tools/Makefile
