THORSANVIL_ROOT             = $(realpath ../../)

TARGET						= PyntHTTP.defer
NAMESPACE					= ThorsAnvil::Nissa
DEFER_NAME					= Nissa
LINK_LIBS					+= ThorsLogging


include $(THORSANVIL_ROOT)/build/tools/Makefile
