THORSANVIL_ROOT             = $(realpath ../../)

TARGET						= PyntHTTP.defer
NAMESPACE					= ThorsAnvil::Nissa
DEFER_NAME					= Nissa
LINK_LIBS					+= ThorsLogging
XFILE_WARNING_FLAGS			+= -Wno-unused-private-field -Wno-unused-parameter


include $(THORSANVIL_ROOT)/build/tools/Makefile
